name: Revoke GitHub Token
description: |
  This action revokes a specified GitHub App installation access token.
  Although these tokens automatically expire after one hour, immediate revocation enhances security.

  To prevent workflow failures, this action **always succeeds**.
  Even if the token has already been revoked or an API error occurs,
  the action will return a success status to prevent workflow disruptions.
  See the [FAQ](#faq) for more details on this behavior.

  ## Usage

  ```yaml
    steps:
      - name: Revoke GitHub Token
        uses: tmknom/revoke-github-token-action@v0
        with:
          token: <your-github-installation-access-token>
  ```

inputs:
  token:
    required: true
    description: The GitHub App installation access token to revoke.

runs:
  using: composite

  steps:
    - name: Revoke
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        curl --location --request DELETE \
          --url "${GITHUB_API_URL}/installation/token" \
          --header "Accept: application/vnd.github+json" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --header "Authorization: Bearer ${TOKEN}" || true
      shell: bash
