name: Revoke GitHub Token
description: |
  This action revokes a specified GitHub App installation access token.
  Although these tokens automatically expire after one hour, manual revocation enhances security.

  To prevent workflow failures, this action **always succeeds**,
  even if the token is already revoked or an error occurs.
  All errors are ignored, allowing workflows to continue running smoothly.
  See the [FAQ](#what-happens-if-the-token-is-already-invalid) for more details on this behavior.

  ## Usage

  ```yaml
    steps:
      - name: Revoke GitHub Token
        uses: tmknom/revoke-github-token-action@v0
        with:
          token: <your-github-installation-access-token>
  ```

inputs:
  token:
    required: true
    description: GitHub App installation access token.

runs:
  using: composite

  steps:
    - name: Revoke
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        curl --location --request DELETE \
          --url "${GITHUB_API_URL}/installation/token" \
          --header "Accept: application/vnd.github+json" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --header "Authorization: Bearer ${TOKEN}" || true
      shell: bash
