name: Revoke GitHub Token
description: |
  This action revokes a specified GitHub App installation access token.
  While these tokens automatically expire after one hour, you can revoke them anytime for added security.

  To prevent workflow failures, this action **always returns a successful status**,
  even if the token has already been revoked or an error occurs during execution.
  All errors, including GitHub API failures, are ignored to ensure workflows run smoothly.
  See the [FAQ](#what-happens-if-the-token-is-already-invalid) for more details on this approach.

  ## Usage

  ```yaml
    steps:
      - name: Revoke GitHub Token
        uses: tmknom/revoke-github-token-action@v0
        with:
          token: <your-gitHub-installation-access-token>
  ```

inputs:
  token:
    required: true
    description: GitHub App installation access token.

runs:
  using: composite

  steps:
    - name: Revoke
      env:
        TOKEN: ${{ inputs.token }}
      run: |
        curl --location --request DELETE \
          --url "${GITHUB_API_URL}/installation/token" \
          --header "Accept: application/vnd.github+json" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --header "Authorization: Bearer ${TOKEN}" || true
      shell: bash
