name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup - generate token
        id: setup
        uses: tmknom/private-generate-github-token-action@41cba24e4afced942f1cebdb7b7bd7335b97e275 # v0.3.1
        with:
          repositories: ${{ vars.REPOSITORY }}

      - name: Setup - check generated token
        env:
          REPOSITORY: ${{ vars.REPOSITORY }}
          FIRST_COMMIT_SHA: ${{ vars.FIRST_COMMIT_SHA }}
          GH_TOKEN: ${{ steps.setup.outputs.token }}
        run: |
          set -x
          message="$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/commits/${FIRST_COMMIT_SHA}" \
            | jq -r '.commit.message')"
          test "$?" = "0"
          test "${message}" = "Initial commit"

      - name: Exercise
        uses: ./
        with:
          token: ${{ steps.setup.outputs.token }}

      - name: Verify
        env:
          REPOSITORY: ${{ vars.REPOSITORY }}
          FIRST_COMMIT_SHA: ${{ vars.FIRST_COMMIT_SHA }}
          GH_TOKEN: ${{ steps.setup.outputs.token }}
        run: |
          set -x
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/commits/${FIRST_COMMIT_SHA}" \
            || ret="$?"
          test "${ret}" = "1"
