name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup - generate token
        id: setup
        uses: tmknom/generate-github-token-action@2f3d76e773e658d0e8457ae6646f92f321194665 # v0.2.1
        with:
          app-id: ${{ secrets.TESTING_APP_ID }}
          app-private-key: ${{ secrets.TESTING_APP_PRIVATE_KEY }}
          repositories: ${{ vars.TESTING_REPOSITORY }}

      - name: Setup - check generated token
        env:
          REPOSITORY: ${{ vars.TESTING_REPOSITORY }}
          INITIAL_COMMIT: ${{ vars.TESTING_REPOSITORY_INITIAL_COMMIT }}
          GH_TOKEN: ${{ steps.setup.outputs.token }}
        run: |
          set -x
          message="$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/commits/${INITIAL_COMMIT}" \
            | jq -r '.commit.message')"
          test "$?" = "0"
          test "${message}" = "Initial commit"

      - name: Exercise
        uses: ./
        with:
          token: ${{ steps.setup.outputs.token }}

      - name: Verify
        env:
          REPOSITORY: ${{ vars.TESTING_REPOSITORY }}
          INITIAL_COMMIT: ${{ vars.TESTING_REPOSITORY_INITIAL_COMMIT }}
          GH_TOKEN: ${{ steps.setup.outputs.token }}
        run: |
          set -x
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GITHUB_REPOSITORY_OWNER}/${REPOSITORY}/commits/${INITIAL_COMMIT}" \
            || ret="$?"
          test "${ret}" = "1"
